### ISSUE TITLE
Delete Menu

### ISSUE THREAD

**Issue by Indicaza** [Indicaza/GiterBot#1]
### TODO

- [x] Fix deleteRow() UI
- [x] Fix checkID() logic
- [x] add drop table functionality

**Comment by Indicaza** [comment]
Cleaned up deleteRow() submenu UI, then lazily replaced checkID() with checkColumn() 
(menus/delete/submenus/deleteRow.js (line 89))

61e276d2b1e2653e58f6304d214046e1fb1ab233

**Comment by Indicaza** [comment]
Done!
